name: Check Markdown Links
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check-markdown-links:
    # https://github.com/marketplace/actions/markup-link-checker-mlc
    name: Markup Link Checker (mlc)
    runs-on: ubuntu-latest
    steps:
      - uses: becheran/mlc@v0.16.0
        # with:
        #   args: ./README.md
